// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ST3610UllTwXmoy16hpao_jeXwCcyp8',
    appId: '1:357188946153:web:871d8ff1a2496692ae8878',
    messagingSenderId: '357188946153',
    projectId: 'tenken-engiflow-app',
    authDomain: 'tenken-engiflow-app.firebaseapp.com',
    storageBucket: 'tenken-engiflow-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcBDsLEdoBz-sW-Ut3I37Vem6u0h7r61U',
    appId: '1:357188946153:android:ea5dbd75623675feae8878',
    messagingSenderId: '357188946153',
    projectId: 'tenken-engiflow-app',
    storageBucket: 'tenken-engiflow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX0rvdG4ADFqX54KA-m5hIDbWWxdU99LA',
    appId: '1:357188946153:ios:f1dfe375b175542fae8878',
    messagingSenderId: '357188946153',
    projectId: 'tenken-engiflow-app',
    storageBucket: 'tenken-engiflow-app.firebasestorage.app',
    iosClientId: '357188946153-te5phle3pej130n6e1ofr80f3dk5hkek.apps.googleusercontent.com',
    iosBundleId: 'com.tenken.engiflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX0rvdG4ADFqX54KA-m5hIDbWWxdU99LA',
    appId: '1:357188946153:ios:f1dfe375b175542fae8878',
    messagingSenderId: '357188946153',
    projectId: 'tenken-engiflow-app',
    storageBucket: 'tenken-engiflow-app.firebasestorage.app',
    iosClientId: '357188946153-te5phle3pej130n6e1ofr80f3dk5hkek.apps.googleusercontent.com',
    iosBundleId: 'com.tenken.engiflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3ST3610UllTwXmoy16hpao_jeXwCcyp8',
    appId: '1:357188946153:web:7c0eb836d65cf707ae8878',
    messagingSenderId: '357188946153',
    projectId: 'tenken-engiflow-app',
    authDomain: 'tenken-engiflow-app.firebaseapp.com',
    storageBucket: 'tenken-engiflow-app.firebasestorage.app',
  );

}